name: Build Java JAR

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init

    - name: setup jdk 11.0
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11

    - name: Build
      run: ./build.sh host-jar "release"

    - uses: actions/upload-artifact@v2
      with:
        path: dist

